version: '3'

services:

  web:
    container_name: neighbors-green
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}
    expose:
      - "8081"
    ports:
      - "8081:8081"
    environment:
      - TZ=Asia/Seoul
      - DB_URL=${DATASOURCE_URL_LOCAL}
      - DB_USERNAME=${DATASOURCE_USERNAME}
      - DB_PASSWORD=${DATASOURCE_PASSWORD}