version: '3'

services:

  web:
    container_name: neighbors-blue
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - TZ=Asia/Seoul
      - DB_URL=${DATASOURCE_URL_LOCAL}
      - DB_USERNAME=${DATASOURCE_USERNAME}
      - DB_PASSWORD=${DATASOURCE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRED_IN=${JWT_EXPIRED_IN}
      - REFRESH_TOKEN_EXPIRED_IN=${REFRESH_TOKEN_EXPIRED_IN}

networks:
  app-network:
    external: true