version: '3'

services:

  web:
    container_name: neighbors-blue
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - TZ=Asia/Seoul
      - DATASOURCE_URL_LOCAL=${DATASOURCE_URL_LOCAL}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRED_IN=${JWT_EXPIRED_IN}
      - REFRESH_TOKEN_EXPIRED_IN=${REFRESH_TOKEN_EXPIRED_IN}
      - KAKAO_CLIENT_KEY=${KAKAO_CLIENT_KEY}
      - KAKAO_REDIRECT_URL=${KAKAO_REDIRECT_URL}
      - KAKAO_REDIRECT_URL_TEST=${KAKAO_REDIRECT_URL_TEST}

networks:
  app-network:
    external: true